### PR TITLE
shiboken: support response files

### PR DESCRIPTION
**Pull request by mathstuf**

### CODE REVIEW

**Comment by mathstuf** [comment]
@mwoehlke-kitware @vibraphone

**Comment by mathstuf** [comment]
So the SMTK side went in without this?

**Comment by mwoehlke-kitware** [comment]
This looks like a useful addition to Shiboken. Have you pushed this to upstream's gerrit?

**Comment by mathstuf** [comment]
No… I can if it works in SMTK though :) .

**Pull request merged**
