### PR TITLE
ShibokenConfig: provide PYTHONPATH as an absolute path

### PR DESCRIPTION
**Pull request by mathstuf**
Consumers of Shiboken may not know Shiboken's install prefix.

### CODE REVIEW

**Comment by vibraphone** [comment]
Will this break ShibokenConfig.cmake in the build dir (because `PYTHON_SITE_PACKAGES` might work but `SBK_PYTHONPATH` will not)? If not, +1.

**Comment by mathstuf** [comment]
Hrm, probably will.

**Comment by vibraphone** [comment]
Was it already broken? If not, I hate to say "spend more time on shiboken," but making shiboken any more infuriating to use/develop is a really bad idea. I might commit hardwareslaughter.

**Comment by mathstuf** [comment]
It was already broken in the sense that you had to put it with `Shiboken_DIR` for it to work in the `PYTHONPATH` environment.

**Comment by vibraphone** [comment]
1. What do you mean "put it with `Shiboken_DIR`"?
2. Currently, running `ctest` in shiboken's build dir works (perhaps because it has already been installed?). I just don't want that (being able to run ctest) to break so that you cannot work on shiboken. It would also be nice if you could point SMTK at a build directory to test out changes without installing.

**Comment by mathstuf** [comment]
Before, it was always a relative path, so you had to know the root to prepend to it to use it in `PYTHONPATH`.

The tests should not care what is in the config file.

**Comment by vibraphone** [comment]
I think it is hard to say whether the build tree is more or less broken with the PR (can't use build-tree in other projects, but you probably couldn't before), so merge it... at least it fixes the install.

**Pull request merged**
